import { Router } from 'express';
import authRoutes from './authRoutes';
import productRoutes from './productRoutes';
import categoryRoutes from './categoryRoutes';
import collectionRoutes from './collectionRoutes';
import wishlistRoutes from './wishlistRoutes';
import cartRoutes from './cartRoutes';
import orderRoutes from './orderRoutes';
import paymentRoutes from './paymentRoutes';
import heroRoutes from './heroRoutes';
import storyRoutes from './storyRoutes';
import lookbookRoutes from './lookbookRoutes';
import moodRoutes from './moodRoutes';
import reviewRoutes from './reviewRoutes';
import couponRoutes from './couponRoutes';
import settingsRoutes from './settingsRoutes';
import bannerRoutes from './bannerRoutes';
import adminRoutes from './adminRoutes';
import uploadRoutes from './uploadRoutes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/categories', categoryRoutes);
router.use('/collections', collectionRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/hero', heroRoutes);
router.use('/stories', storyRoutes);
router.use('/lookbooks', lookbookRoutes);
router.use('/moods', moodRoutes);
router.use('/reviews', reviewRoutes);
router.use('/coupons', couponRoutes);
router.use('/banners', bannerRoutes);
router.use('/settings', settingsRoutes);
router.use('/admin', adminRoutes);
router.use('/upload', uploadRoutes);

export default router;
